# AHP ranking for Task3-Cottbus DRT parameter sets
#
# This script follows the AHP structure used in the LCA tutorial:
# 1. Build one pairwise comparison matrix for alternatives under each criterion.
# 2. Bundle these matrices in APCL.
# 3. Define one pairwise comparison matrix for the criteria, CWPC.
# 4. Compute final AHP scores from principal eigenvectors.
#
# Main references / rationale:
# - Saaty, T. L. (1980). The Analytic Hierarchy Process. McGraw-Hill.
# - ITS DRT lecture: DRT insertion objectives include maximizing request
#   acceptance rate, minimizing passenger ride time, minimizing operation time,
#   and minimizing fleet size.
# - Ricard et al. (2021): reliability is an important aspect of public transport
#   service quality.
# - Gerzinic et al. (2023): waiting-time variability affects travellers'
#   perception and future choices; cancelled service has strong disutility.
# - Zang et al. (2022): travel time reliability is a core concern for travellers,
#   operators, planners, and managers.
#
# Note:
# The exact Saaty scores in CWPC are our group judgement. The references support
# the relative importance logic, not a universal fixed matrix for Cottbus.

assignment_dir <- "D:/Study/TUB/So2026/ITS/GroupAssignment/ITS-Homework2/Assignment_2"
base_dir <- file.path(assignment_dir, "Task3-Cottbus")
input_csv <- file.path(base_dir, "output", "scenario_metrics_summary.csv")
output_dir <- file.path(assignment_dir, "outputs")
plot_dir <- file.path(output_dir, "ahp_plots")

if (!dir.exists(plot_dir)) {
  dir.create(plot_dir, recursive = TRUE)
}

# Remove old figures so the folder contains only the figures generated by this run.
old_png <- list.files(plot_dir, pattern = "\\.png$", full.names = TRUE)
if (length(old_png) > 0) {
  file.remove(old_png)
}

metrics <- read.csv(input_csv, stringsAsFactors = FALSE, check.names = FALSE)
alternatives <- metrics$Set
rownames(metrics) <- alternatives

# Use the most precise output columns from the simulation summary.
# The *_min values in the CSV are rounded; therefore, we recompute minutes
# from the original second-based columns for all calculations and plots.
metrics$avgWait_min_exact <- metrics$avgWait_s / 60
metrics$p95Wait_min_exact <- metrics$p95Wait_s / 60
metrics$totalTravelTime_min_exact <- metrics$totalTravelTime_s / 60

# -------------------------------
# 1. AHP helper functions
# -------------------------------

getWeights <- function(mat) {
  eigen_result <- eigen(mat)
  max_index <- which.max(Re(eigen_result$values))
  eigenvec <- Re(eigen_result$vectors[, max_index])
  weights <- abs(eigenvec)
  weights <- weights / sum(weights)
  return(weights)
}

AHP <- function(criteria_weights, alternatives_mats) {
  criteria_w <- getWeights(criteria_weights)
  alt_weights <- sapply(alternatives_mats, getWeights)
  result <- alt_weights %*% criteria_w
  return(as.vector(result))
}

consistencyRatio <- function(mat) {
  n <- nrow(mat)
  if (n <= 2) {
    return(0)
  }

  lambda_max <- max(Re(eigen(mat)$values))
  ci <- (lambda_max - n) / (n - 1)

  ri_table <- c(
    "1" = 0.00, "2" = 0.00, "3" = 0.58, "4" = 0.90,
    "5" = 1.12, "6" = 1.24, "7" = 1.32, "8" = 1.41,
    "9" = 1.45, "10" = 1.49
  )

  ri <- ri_table[as.character(n)]
  if (is.na(ri) || ri == 0) {
    return(0)
  }

  return(ci / ri)
}

# -------------------------------
# 2. Convert observed differences to Saaty scale
# -------------------------------
#
# For each criterion, the direction of preference comes from the simulation
# result. For example, under average waiting time, a lower value is better.
# The strength of preference is then mapped to Saaty's 1-9 scale according to
# the relative difference between two alternatives.
#
# Example:
# S5 avg wait = 7.51 min, S1 avg wait = 9.17 min.
# Relative difference = (9.17 - 7.51) / 7.51 = 22.1%.
# This falls in the 20%-30% range, so S5 is assigned a Saaty value of 6 over S1.
# The reciprocal entry is therefore 1/6.

gapToSaaty <- function(relative_gap) {
  if (relative_gap < 0.01) {
    return(1)
  } else if (relative_gap < 0.03) {
    return(2)
  } else if (relative_gap < 0.07) {
    return(3)
  } else if (relative_gap < 0.12) {
    return(4)
  } else if (relative_gap < 0.20) {
    return(5)
  } else if (relative_gap < 0.30) {
    return(6)
  } else if (relative_gap < 0.45) {
    return(7)
  } else if (relative_gap < 0.65) {
    return(8)
  } else {
    return(9)
  }
}

buildSaatyMatrix <- function(values, direction = "cost") {
  n <- length(values)
  mat <- matrix(1, nrow = n, ncol = n)

  for (i in 1:n) {
    for (j in 1:n) {
      if (i == j) {
        mat[i, j] <- 1
      } else {
        if (direction == "cost") {
          better_i <- values[i] < values[j]
          better_j <- values[j] < values[i]
          better_value <- min(values[i], values[j])
          worse_value <- max(values[i], values[j])
        } else if (direction == "benefit") {
          better_i <- values[i] > values[j]
          better_j <- values[j] > values[i]
          better_value <- max(values[i], values[j])
          worse_value <- min(values[i], values[j])
        } else {
          stop("direction must be either 'cost' or 'benefit'")
        }

        if (better_value == 0 && worse_value == 0) {
          scale_value <- 1
        } else if (better_value == 0) {
          scale_value <- 9
        } else {
          relative_gap <- abs(worse_value - better_value) / abs(better_value)
          scale_value <- gapToSaaty(relative_gap)
        }

        if (better_i) {
          mat[i, j] <- scale_value
        } else if (better_j) {
          mat[i, j] <- 1 / scale_value
        } else {
          mat[i, j] <- 1
        }
      }
    }
  }

  rownames(mat) <- alternatives
  colnames(mat) <- alternatives
  return(mat)
}

buildReliabilityMatrix <- function(rejections) {
  n <- length(rejections)
  mat <- matrix(1, nrow = n, ncol = n)

  for (i in 1:n) {
    for (j in 1:n) {
      if (i == j || rejections[i] == rejections[j]) {
        mat[i, j] <- 1
      } else if (rejections[i] == 0 && rejections[j] > 0) {
        # A rejected request means service failure for that passenger.
        # Based on this service-reliability interpretation, a zero-rejection
        # alternative is very strongly preferred over a rejected alternative.
        mat[i, j] <- 7
      } else if (rejections[i] > 0 && rejections[j] == 0) {
        mat[i, j] <- 1 / 7
      } else {
        better_i <- rejections[i] < rejections[j]
        better_value <- min(rejections[i], rejections[j])
        worse_value <- max(rejections[i], rejections[j])
        relative_gap <- (worse_value - better_value) / max(1, better_value)
        scale_value <- gapToSaaty(relative_gap)
        mat[i, j] <- ifelse(better_i, scale_value, 1 / scale_value)
      }
    }
  }

  rownames(mat) <- alternatives
  colnames(mat) <- alternatives
  return(mat)
}

# -------------------------------
# 3. Pairwise comparison matrix for each criterion
# -------------------------------

avg_wait <- buildSaatyMatrix(metrics$avgWait_min_exact, "cost")
p95_wait <- buildSaatyMatrix(metrics$p95Wait_min_exact, "cost")
total_travel_time <- buildSaatyMatrix(metrics$totalTravelTime_min_exact, "cost")
reliability <- buildReliabilityMatrix(metrics$rejections)
idle_vehicle_share <- buildSaatyMatrix(metrics$minShareIdleVehicles, "cost")
environmental_efficiency <- buildSaatyMatrix(metrics$dp_dt, "benefit")

# Check reciprocal condition for alternative matrices.
avg_wait == t(1 / avg_wait)
p95_wait == t(1 / p95_wait)
total_travel_time == t(1 / total_travel_time)
reliability == t(1 / reliability)
idle_vehicle_share == t(1 / idle_vehicle_share)
environmental_efficiency == t(1 / environmental_efficiency)

APCL <- list(
  avg_wait = avg_wait,
  p95_wait = p95_wait,
  total_travel_time = total_travel_time,
  reliability = reliability,
  idle_vehicle_share = idle_vehicle_share,
  environmental_efficiency = environmental_efficiency
)

# -------------------------------
# 4. Pairwise comparison matrix for the criteria
# -------------------------------
#
# Criteria rationale:
#
# Since our decision-making focuses on DRT service quality, service reliability
# and passenger waiting experience receive the highest priority. A rejected
# request means the DRT system fails to serve a passenger, so reliability is
# assigned the highest importance. Extreme waiting time (P95) is slightly more
# important than average waiting time because it captures the worst passenger
# experience and fairness. Average waiting time remains a central passenger
# experience metric. Total travel time is important, but DRT pooling naturally
# allows some detour, so it is lower than reliability and waiting-time criteria.
# Operational efficiency and environmental efficiency are included as supporting
# criteria, but they are less important than direct service-quality criteria.
#
# Based on this reasoning:
# - reliability is 2 times more important than avg_wait,
#   equally to slightly more important than p95_wait,
#   3 times more important than total_travel_time,
#   7 times more important than idle_vehicle_share,
#   and 9 times more important than environmental_efficiency.
# - p95_wait is 2 times more important than avg_wait because it captures
#   extreme passenger experience; it is 3 times more important than total
#   travel time and 5-7 times more important than the supporting indicators.
# - avg_wait is 2 times more important than total_travel_time,
#   5 times more important than idle_vehicle_share,
#   and 7 times more important than environmental_efficiency.
# - idle_vehicle_share is moderately more important than d_p/d_t in this
#   operational study because too many idle vehicles directly imply an oversized
#   DRT fleet and high operating cost.

criteria <- names(APCL)

CWPC <- matrix(c(
  1,   1/2, 2,   1/2, 5,   7,
  2,   1,   3,   1,   5,   7,
  1/2, 1/3, 1,   1/3, 3,   5,
  2,   1,   3,   1,   7,   9,
  1/5, 1/5, 1/3, 1/7, 1,   2,
  1/7, 1/7, 1/5, 1/9, 1/2, 1
),
nrow = length(APCL),
ncol = length(APCL),
byrow = TRUE,
dimnames = list(names(APCL), names(APCL)))

# Check reciprocal condition for criteria matrix.
CWPC == t(1 / CWPC)

# -------------------------------
# 5. Compute AHP results
# -------------------------------

criteria_weights <- getWeights(CWPC)
names(criteria_weights) <- criteria

alternative_weights <- sapply(APCL, getWeights)
final_score <- AHP(CWPC, APCL)

ranking <- data.frame(
  Set = alternatives,
  vehiclesFile = metrics$vehiclesFile,
  fleetSize = metrics$fleetSize,
  maxWaitTime_s = metrics$maxWaitTime_s,
  targetAlpha = metrics$targetAlpha,
  targetBeta = metrics$targetBeta,
  avgWait_min = metrics$avgWait_min_exact,
  p95Wait_min = metrics$p95Wait_min_exact,
  totalTravelTime_min = metrics$totalTravelTime_min_exact,
  rejections = metrics$rejections,
  minShareIdleVehicles = metrics$minShareIdleVehicles,
  dp_dt = metrics$dp_dt,
  AHP_score = as.vector(final_score),
  rank = rank(-as.vector(final_score), ties.method = "min"),
  stringsAsFactors = FALSE
)

ranking <- ranking[order(ranking$rank), ]

zero_rejection_ranking <- ranking[ranking$rejections == 0, ]
zero_rejection_ranking$rank_zero_rejection <- rank(
  -zero_rejection_ranking$AHP_score,
  ties.method = "min"
)
zero_rejection_ranking <- zero_rejection_ranking[
  order(zero_rejection_ranking$rank_zero_rejection),
]

consistency <- data.frame(
  matrix_name = c("CWPC_criteria", names(APCL)),
  consistency_ratio = c(
    consistencyRatio(CWPC),
    sapply(APCL, consistencyRatio)
  ),
  stringsAsFactors = FALSE
)

# -------------------------------
# 6. Write matrices and results
# -------------------------------

write.csv(round(CWPC, 4), file.path(output_dir, "ahp_matrix_criteria.csv"))

for (matrix_name in names(APCL)) {
  write.csv(
    round(APCL[[matrix_name]], 4),
    file.path(output_dir, paste0("ahp_matrix_", matrix_name, ".csv"))
  )
}

write.csv(
  data.frame(criteria = names(criteria_weights), weight = criteria_weights),
  file.path(output_dir, "ahp_criteria_weights.csv"),
  row.names = FALSE
)

write.csv(
  alternative_weights,
  file.path(output_dir, "ahp_alternative_weights_by_criterion.csv")
)

write.csv(
  ranking,
  file.path(output_dir, "ahp_ranking_all_scenarios.csv"),
  row.names = FALSE
)

write.csv(
  zero_rejection_ranking,
  file.path(output_dir, "ahp_ranking_zero_rejection_scenarios.csv"),
  row.names = FALSE
)

write.csv(
  consistency,
  file.path(output_dir, "ahp_consistency_ratios.csv"),
  row.names = FALSE
)

# -------------------------------
# 7. Generate bar plots
# -------------------------------

plotBar <- function(values, title, ylab, file_name, lower_is_better = FALSE) {
  png(file.path(plot_dir, file_name), width = 1200, height = 800, res = 140)
  colors <- rep("#5B9BD5", length(values))
  best_index <- if (lower_is_better) which.min(values) else which.max(values)
  colors[best_index] <- "#70AD47"
  barplot(
    values,
    names.arg = alternatives,
    col = colors,
    main = title,
    ylab = ylab,
    xlab = "Scenario",
    ylim = c(0, max(values) * 1.15)
  )
  grid(nx = NA, ny = NULL, col = "gray85")
  dev.off()
}

plotPie <- function(values, title, file_name) {
  png(file.path(plot_dir, file_name), width = 1200, height = 800, res = 140)
  piepercent <- round(100 * values / sum(values), 1)
  pie(
    values,
    labels = paste0(piepercent, "%"),
    col = c(
      "lightblue", "mistyrose", "lightcyan", "lavender",
      "cornsilk", "thistle4", "steelblue4", "palegreen"
    )[seq_along(values)],
    radius = 1,
    main = title
  )
  legend(
    "bottomleft",
    names(values),
    cex = 0.8,
    fill = c(
      "lightblue", "mistyrose", "lightcyan", "lavender",
      "cornsilk", "thistle4", "steelblue4", "palegreen"
    )[seq_along(values)]
  )
  dev.off()
}

# Raw performance plots for each criterion.
plotBar(
  metrics$avgWait_min_exact,
  "Average waiting time by scenario",
  "Minutes",
  "criterion_avg_wait_raw.png",
  lower_is_better = TRUE
)

plotBar(
  metrics$p95Wait_min_exact,
  "P95 waiting time by scenario",
  "Minutes",
  "criterion_p95_wait_raw.png",
  lower_is_better = TRUE
)

plotBar(
  metrics$totalTravelTime_min_exact,
  "Total travel time by scenario",
  "Minutes",
  "criterion_total_travel_time_raw.png",
  lower_is_better = TRUE
)

plotBar(
  metrics$rejections,
  "Rejected requests by scenario",
  "Rejected requests",
  "criterion_rejections_raw.png",
  lower_is_better = TRUE
)

plotBar(
  metrics$minShareIdleVehicles,
  "Minimum share of idle vehicles by scenario",
  "Share",
  "criterion_idle_share_raw.png",
  lower_is_better = TRUE
)

plotBar(
  metrics$dp_dt,
  "Environmental efficiency proxy by scenario",
  "d_p/d_t",
  "criterion_dp_dt_raw.png",
  lower_is_better = FALSE
)

# Final ranking bar chart. This is the 7th bar chart.
png(file.path(plot_dir, "final_ahp_ranking.png"), width = 1200, height = 800, res = 140)
rank_plot_values <- ranking$AHP_score
names(rank_plot_values) <- ranking$Set
barplot(
  rank_plot_values,
  col = "#70AD47",
  main = "Final AHP ranking",
  ylab = "AHP score",
  xlab = "Scenario",
  ylim = c(0, max(rank_plot_values) * 1.2)
)
grid(nx = NA, ny = NULL, col = "gray85")
dev.off()

final_pie_values <- ranking$AHP_score
names(final_pie_values) <- ranking$Set
plotPie(
  final_pie_values,
  "Ranking of DRT scenarios using AHP",
  "final_ahp_ranking_pie.png"
)

# -------------------------------
# 8. Console output
# -------------------------------

cat("\nCriteria pairwise comparison matrix (CWPC):\n")
print(round(CWPC, 4))

cat("\nCriteria weights:\n")
print(round(criteria_weights, 4))

cat("\nAHP final ranking, all scenarios:\n")
print(ranking[, c("Set", "AHP_score", "rank", "rejections")])

cat("\nAHP final ranking, zero-rejection scenarios only:\n")
print(zero_rejection_ranking[, c(
  "Set", "AHP_score", "rank_zero_rejection", "rejections"
)])

cat("\nConsistency ratios:\n")
print(consistency)

cat("\nOutput CSV files written to:\n")
cat(output_dir, "\n")

cat("\nPlots written to:\n")
cat(plot_dir, "\n")
